# Disable all limiter protections for API access
# This allows n8n and other tools to connect without restrictions

[botdetection.ip_limit]
# Disable IP rate limiting completely
link_token = false

[botdetection.ip_lists]
# Empty block and pass lists - allow all IPs
block_ip = []
pass_ip = []
pass_searxng_org = false

# Disable all HTTP header checks
[botdetection.http_accept]
filter = false

[botdetection.http_accept_encoding]
filter = false

[botdetection.http_accept_language]
filter = false

[botdetection.http_user_agent]
filter = false
