# see https://docs.searxng.org/admin/settings/settings.html#settings-use-default-settings
use_default_settings: true
server:
  # base_url is defined in the SEARXNG_BASE_URL environment variable, see .env and docker-compose.yml
  secret_key: "1390b9fea7fade0937fd2df3a97ad9c6b416f28bb083a56583bc6f129c578af1"  # change this!
  limiter: false  # disable rate limiting for public API access
  image_proxy: true
redis:
  url: redis://redis:6379/0

search:
  formats:
    - html
    - json
